# Generated by Django 3.0.3 on 2020-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoriess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('model', models.TextField()),
                ('size', models.TextField()),
                ('whenCame', models.DateField(auto_now_add=True)),
                ('whenGone', models.DateField(blank=True, null=True)),
                ('gone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Beginners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('size', models.FloatField()),
                ('whenCame', models.DateField(auto_now_add=True)),
                ('whenGone', models.DateField(blank=True, null=True)),
                ('gone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('year', models.IntegerField(auto_created=True, editable=False)),
                ('size', models.FloatField(auto_created=True, editable=False)),
                ('model', models.TextField(auto_created=True, editable=False)),
                ('category', models.TextField(auto_created=True, editable=False)),
                ('type', models.TextField(auto_created=True, editable=False)),
                ('serial', models.TextField(max_length=6, primary_key=True, serialize=False)),
                ('whenCame', models.DateField(auto_now_add=True)),
                ('whenGone', models.DateField(blank=True, null=True)),
                ('whenSold', models.DateField(blank=True, null=True)),
                ('repair', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sail',
            fields=[
                ('year', models.IntegerField(auto_created=True, editable=False)),
                ('size', models.FloatField(auto_created=True, editable=False)),
                ('model', models.TextField(auto_created=True, editable=False)),
                ('category', models.TextField(auto_created=True, editable=False)),
                ('type', models.TextField(auto_created=True, editable=False)),
                ('serial', models.TextField(max_length=8, primary_key=True, serialize=False)),
                ('whenCame', models.DateField(auto_now_add=True)),
                ('whenGone', models.DateField(blank=True, null=True)),
                ('whenSold', models.DateField(blank=True, null=True)),
                ('repair', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
