# Generated by Django 3.0.3 on 2020-04-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginners',
            name='type',
            field=models.TextField(default='Board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beginners',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='whenGone',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='whenSold',
            field=models.DateField(null=True),
        ),
    ]
