# Generated by Django 3.0.3 on 2020-04-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rene', '0002_auto_20200406_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginners',
            name='size',
            field=models.TextField(),
        ),
    ]
