# Generated by Django 3.0.3 on 2020-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rene', '0003_auto_20200408_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='size',
            field=models.IntegerField(auto_created=True, editable=False),
        ),
    ]
