# Generated by Django 3.0.3 on 2020-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rene', '0004_auto_20200411_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='brand',
            field=models.TextField(auto_created=True, default='JP Australia', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sail',
            name='brand',
            field=models.TextField(auto_created=True, default='Severne', editable=False),
            preserve_default=False,
        ),
    ]
